# Site settings
author: Chris Beyer
title: Why I decided to learn software engineering
header-img: img/home-bg.png
email: beyercorpuz@gmail.com
copyright_name: Chris Beyer
description: > # this means to ignore newlines until "baseurl:"
  A labor of love
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: beyermusic
github_username:  beyercorpuz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
